### ISSUE TITLE
Files are overwritten

### ISSUE THREAD

**Issue by Mi-Pe** [boberle/vinted-downloader#6]
Subsequently downloaded images are titled "photo_<number>.jpg", and after downloading photos of more items in a row, previous files are overwritten. Is there a way to prevent it? Probably best would be to add the item name as part of the image file title - that would also help organize files. Otherwise, we have to manually rename files after each download.

**Comment by boberle** [comment]
Yes, I know, this is a bit annoying. Is it OK if I add an option `--save-in-dir` that creates a directory using the item name and put the pictures inside? Or do you prefer adding the name of the item in the picture name?

**Comment by Mi-Pe** [comment]
You mean it would be a subdirectory of the download folder, right? If so, then yes, that's a good solution! Even better if it takes you less time than renaming files.

**Comment by boberle** [comment]
Yes, this is it. I'll do it this morning (Paris time).

**Comment by Mi-Pe** [comment]
No rush needed, thanks a lot!

**Comment by boberle** [comment]
It's done. You can update the package with:

```bash
pip install --upgrade vinted-downloader
```

Then, to save in a subdir of the current directory, use:

```bash
python3 vinted_downloader.py --save-in-dir "https://www.vinted.fr/items/1234-item-title"
```

This will save the pictures in `./1234-item-title`.

If you want to save in `./my-ouput/1234-item-title` for example, add the `-o my-output` option:

```bash
python3 vinted_downloader.py -o my-output --save-in-dir "https://www.vinted.fr/items/1234-item-title"
```

The directories are created automatically if they don't already exist.

**Comment by Mi-Pe** [comment]
Thanks for the upgrade, but it's not working for me.
Upgraded the script, run the <python3 vinted_downloader.py --save-in-dir "URL"> command, and I get this error:

![-2024-mar-17-002](https://github.com/boberle/vinted-downloader/assets/73021367/673df8dd-0639-4891-b906-00ec64ae4905)

which means "cannot" in broken Polish (it's not even a full phrase) and it returns to the folder. No files are created. I tried removing Python, rebooting PC, and installing Python again, along with the vinted downloader, but the result is the same. Do you have any idea what might be the reason?

**Comment by boberle** [comment]
Oh, sorry, it should be `python`, not `python3`. I guess want is "cannot" do is finding `python3`...

**Comment by Mi-Pe** [comment]
![-2024-mar-17-012](https://github.com/boberle/vinted-downloader/assets/73021367/6f0b4cbd-0c50-4639-acd8-c71196ef0faa)
Since I installed the vinted-downloader script, it doesn't matter from what folder I run the command prompt, right? The error appears even if I run the command from the Downloads folder, or the folder where I store the ZIP installers.

**Comment by boberle** [comment]
Oh, yeah, my bad:

```
python -m vinted_downloader --save-in-dir "URL"
```

I'm really sorry, but I've mixed Linux/Windows, sources/not sources when copy-pasting.

**Comment by Mi-Pe** [comment]
Haha, no problem! Third time lucky, as they say. Without you, I wouldn't do it at all, so thanks a lot! Closing the issue.
